In [0]:
import numpy as np
A = np.ndarray(shape=(2,3),dtype= 'int')
print(A.shape)
print('Number of Rows ',A.shape[0])
print('Number Columns ',A.shape[1])

(2, 3)
Number of Rows  2
Number Columns  3


In [0]:
for i in range(A.shape[0]):
  for j in range(A.shape[1]):
    A[i][j] = input()

print(A)

1
2
3
4
5
6
[[1 2 3]
 [4 5 6]]


In [0]:
C = np.arange(1,5).reshape(2,-1)  #reshape(2,-1)
D = np.arange(1,5).reshape(2,2)
print(C)
print(D)
print('Simple Array Multiplication')
print(C * D)
print('Matrix Multiplication')
print(C@D)
print(C.T)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
Simple Array Multiplication
[[ 1  4]
 [ 9 16]]
Matrix Multiplication
[[ 7 10]
 [15 22]]
[[1 3]
 [2 4]]


In [0]:
arr = np.repeat(6,8).reshape(2,4)
print(arr)

[[6 6 6 6]
 [6 6 6 6]]


In [0]:
s =90
class Student:
  name = 'Potter'
  id_number = 1234
  
  def __new__(self,*args):
    print('New function is called')
    student = object.__new__(self)
    return student

  def __repr__(self):
    return (f'student Name {self.name},and his id is {str(self.id_number)}')
    
  def __init__(self,name,id):
    self.name = name
    self.id_number = id 
  def add_student(self):
    print('Please Enter Details of new student is')
    self.name = input('Enter name ')
    self.id_number = int(input('Enter ID'))

student1 = Student('John',98989)
print(student1)
student1.add_student()
student1



New function is called
student Name John,and his id is 98989
Please Enter Details of new student is
Enter name arun
Enter ID123345


student Name arun,and his id is 123345