In [0]:
def strChange(text):
  return text.upper()+'!'
#strChange('talentsprint')
example = strChange
example('testdata')

# lambda text : text.upper()

'TESTDATA!'

In [0]:
def sample_functionpass(text,f):
  return f(text)

sample_functionpass('habeeb',strChange)

'HABEEB!'

![alt text](https://raw.githubusercontent.com/mdhabeebvulla/samples/master/shape2.png)

In [0]:
from math import pi,sqrt
def rsquare(r):
  return r*r 
# 1 , pi ,3sqrt(3)*0.5

def shape_area(r,rsquare,const):
  return rsquare(r)*const

print('Area of Square is  ',shape_area(3,rsquare,1))
print('Area of circle is  ',shape_area(3,rsquare,pi))
print('Area of hexagon is  ',shape_area(3,rsquare,3*sqrt(3)*0.5))

def shape_area(r,const):
  return (lambda r : r * r)(r)*const


Area of Square is   9
Area of circle is   28.274333882308138
Area of hexagon is   23.382685902179844


In [0]:
a = lambda r : r * r
print(a(3))

9


In [0]:
print((lambda r : r * r)(3))

9


In [0]:
t = lambda x : x+2 if x>=30 else x+10
print(t(50))

#lambda parameter : return 

52


#MAP



In [0]:
sample_lst = ['Hyderabad','PUNE','chennai','Banglore']

new_lst = list(map(str.capitalize,sample_lst))
lambda_lst = list(map(lambda s : s[:1].upper() + s[1:].lower(),sample_lst))

new_len =list(map(len,sample_lst))

print(new_lst)
print(lambda_lst)
print(new_len)
[(lambda s:s.lower())(s) for s in sample_lst]


['Hyderabad', 'Pune', 'Chennai', 'Banglore']
['Hyderabad', 'Pune', 'Chennai', 'Banglore']
[9, 4, 7, 8]


#FILTER


In [0]:
sample_lst = ['Hyderabad','PUNE','chennai','Banglore','Humayunnagar']

new_filter = list(filter(lambda s :s.startswith('H'),sample_lst)) 

print(new_filter)


['Hyderabad', 'Humayunnagar']


#REDUCE


In [0]:
import operator

from functools import reduce
funcs = [str.upper ,str.lower.str.capitalize]

result = reduce(operator.mul,[1,2,3,4,5])

print(result)
operator?

120


In [0]:
import numpy as np
arr1 = np.arange(500)
list_arr = range(500)

%timeit -n10 x =[val * 5 for val in list_arr]
%timeit -n10 y = arr1*5

10 loops, best of 3: 44.9 µs per loop
10 loops, best of 3: 2.14 µs per loop


In [0]:
scalar = np.array(2)
print(scalar) #scalar 

vector1 = np.array([1, 2, 3, 4, 5])
print(vector1)

matr = np.array([[1,2],[3,4]])
print(matr)
print()
tens = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print(tens)

2
[1 2 3 4 5]
[[1 2]
 [3 4]]

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
